version: '3'

services:
  with-docker-multi-env-staging:
    build:
      context: ../../
      dockerfile: docker/staging/Dockerfile
    image: with-docker-multi-env-staging
    ports:
      - '3011:3000'